### ISSUE TITLE
Getting Syntax errors

### ISSUE THREAD

**Issue by giterest** [hotplot/enviroplus-mqtt#2]
Hi, can you please help me? I've edited /etc/systemd/system/envlogger.service as follows;

ExecStart=/usr/bin/python3 -u /usr/src/enviroplus-mqtt/src/main.py -host XX.XX.XX.XX --port 1883 --username 'XXX' --password 'XXX' --prefix 'outdoor/wetterstation' but I keep getting

File "main.py", line 47
    sys.exit(f"Connecting to the MQTT server failed: {logger.connection_error}")
                                                                              ^
SyntaxError: invalid syntax

**Comment by ferazambuja** [comment]
Double-check the attributes documentation and try this:

-h XXX.XXX.XXX.XXX -p 1883 -U username -P password --prefix outdoor/wetterstation --interval 10

**Comment by giterest** [comment]
Hi, thanks for reply! Tried this (/w my parameters of course), but same result / error.

**Comment by hotplot** [comment]
Hi @giterest 

There are two issues here:

1) The connection to your MQTT server is failing, probably because of an authentication error or similar, or possibly incompatibility with your installed version of `paho.mqtt`
2) You are running with Python 2 rather than Python 3, which doesn't support the format string syntax used to log the connection error.

Have you verified that you can connect to the MQTT server using those credentials with an app such as MQTTBox?

I would strongly recommend using Python 3. I have not tested at all using Python 2

**Comment by gcaley** [comment]
I had the same problem, i changed the logger.py line from:
self.client.connect(host,port)
to the following 
self.client.connect("192.168.2.148",1883,60)
I think the error is actually a lack of quotes around the IP address, for good measure i added a timeout, especially as my enviroplus is in the garden.
